# Generated by Django 5.1.8 on 2025-04-26 21:38

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="부제"
            ),
        ),
    ]
